# Generated by Django 5.1.7 on 2025-03-24 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('asset_type', models.CharField(choices=[('savings', 'Savings'), ('fixed_income BR', 'Fixed Income BR'), ('stock_br', 'Stock BR'), ('real_state_br', 'Real State (BR)'), ('savings', 'Savings'), ('stock_us', 'Stock US'), ('long_time_inv', 'Long Time Investiment'), ('fixed_income US', 'Fixed Income US'), ('real_state_us', 'Real State (US)'), ('emergency_fund', 'Emergency Fund'), ('crypto', 'Cryptocurrency')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_type', models.CharField(choices=[('prefixed', 'Prefixed'), ('post_fixed', 'Post Fixed'), ('hybrid', 'Hybrid')], max_length=20)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('currency_type', models.CharField(choices=[('usd', 'USD $'), ('brl', 'BRL R$')], max_length=10)),
                ('expire_date', models.DateField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.asset')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.broker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
