# Generated by Django 5.1.7 on 2025-03-24 21:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_asset_asset_type_alter_asset_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('asset', 'transaction_type', 'quantity', 'price_per_unit', 'date'), name='unique_asset_transaction_type_quantity_price_per_unit_date'),
        ),
    ]
